<a href="https://colab.research.google.com/github/bgarcia360/Google_colab/blob/main/Address_clean_up.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
from google.colab import files
import io

Upload the cvs file and covert it to a dataframe

In [12]:
url='https://raw.githubusercontent.com/bgarcia360/data_sets_for_colab/main/address_sample.csv'
address=pd.read_csv(url)
address.head()

#uncoment if you want to upload a file 
#uploaded = files.upload()
#data = io.BytesIO(uploaded['sample.csv'])  #change the csv to upload data file
#address = pd.read_csv(data )

              address
0   1155 Kingsbury St
1    425 W 4th Street
2      602 Waller St.
3  1881 Congress Ave.
4     206 W. 14th St.

Function that clean up the address using regex with boundary.

In [14]:
def add_clean(address):
  import re
  address = re.sub("[^a-zA-Z0-9 ]+","",address) 
  address =address.lower() 
  
  toReplace = {"st": 'Street', "rd": "Road", "ave": "Avenue","dr":"Drive","blvd":"BOULEVARD", "w":"West", "n":"North","e":"East","s":"South"} 
  for k,v in toReplace.items():
    address = re.sub(r"\b" + k + r"\b", v, address)

  address=address.strip().title()
  
  return address

Using the Lambda and apply to apply to append to data frame

In [15]:
address['ouput']= address['address'].apply(lambda x: add_clean(x))

address

                                 address                                 ouput
0                      1155 Kingsbury St                 1155 Kingsbury Street
1                       425 W 4th Street                   425 West 4Th Street
2                         602 Waller St.                     602 Waller Street
3                     1881 Congress Ave.                  1881 Congress Avenue
4                        206 W. 14th St.                  206 West 14Th Street
5                        700 W. 12th St.                  700 West 12Th Street
6                         1231 West Ave.                      1231 West Avenue
7                           991 East 5th                          991 East 5Th
8                           64 Rainey St                      64 Rainey Street
9                       1301 Toomey Road                      1301 Toomey Road
10                            2772 E 7th                         2772 East 7Th
11                       1308 W. 6th St.                  1308 West 6Th Street
12                     800 Guadalupe St.                  800 Guadalupe Street
13                 2322 Red River Street                 2322 Red River Street
14                       1789 Brazos St.                    1789 Brazos Street
15                     Barton Springs Rd                   Barton Springs Road
16                        601 Lavaca St.                     601 Lavaca Street
17                            311 Nueces                            311 Nueces
18                400 Barton Springs Rd.               400 Barton Springs Road
19                           1000 Brazos                           1000 Brazos
20                  300 E. Riverside Dr.              300 East Riverside Drive
21                 124 W Cesar Chavez St          124 West Cesar Chavez Street
22               2200 William Barton Dr.             2200 William Barton Drive
23  Presented by Austin Parks Foundation  Presented By Austin Parks Foundation
24                     Barton Springs Rd                   Barton Springs Road
25                           1 Rainey St                       1 Rainey Street
26                    910 Trinity Street                    910 Trinity Street
27                      710 W. 22 1/2 St                 710 West 22 12 Street
28                 5104 East 5th. Street                  5104 East 5Th Street
29                 1199 S. Congress Ave.            1199 South Congress Avenue
30                        111 E. 8th St.                   111 East 8Th Street
31                        601 Lavaca St.                     601 Lavaca Street
32                    1090 Congress Ave.                  1090 Congress Avenue
33                     750 Lavaca Street                     750 Lavaca Street
34     Presented by The Austin Chronicle     Presented By The Austin Chronicle
35              1530 Barton Springs Road              1530 Barton Springs Road
36                    606 Trinity Street                    606 Trinity Street
37                     600 Congress Ave.                   600 Congress Avenue
38                           E. 21st St.                      East 21St Street
39                           E. 23rd St.                      East 23Rd Street
40                       310 E. 11th St.                  310 East 11Th Street
41                           212 Trinity                           212 Trinity
42                     761 Red River St.                  761 Red River Street
43                       1501 E. 5th St.                  1501 East 5Th Street
44            Presented by Austin Energy            Presented By Austin Energy
45                1201 San Jacinto Blvd.            1201 San Jacinto Boulevard
46              Federal Courthouse Plaza              Federal Courthouse Plaza
47                  305 S. Congress Ave.             305 South Congress Avenue
48                 2401 Lake Austin Blvd            2401 Lake Austin Boulevard